#!/bin/sh

if [ "x$1" = "x0" ]; then
  # Set environment variable containing queue name
  env_idx=0
  env_var="joboption_env_$env_idx"
  while [ -n "${!env_var}" ]; do
     env_idx=$((env_idx+1))
     env_var="joboption_env_$env_idx"
  done
  export RUNTIME_ENABLE_MULTICORE_SCRATCH=1
  eval joboption_env_$env_idx="NORDUGRID_ARC_QUEUE=$joboption_queue"
fi

if [ "x$1" = "x1" ]; then
  # Set grid environment
  if [ -e /etc/profile.d/env.sh ]; then
     source /etc/profile.d/env.sh
  fi
  if [ -e /etc/profile.d/grid-env.sh ]; then
     source /etc/profile.d/grid-env.sh
  fi
  if [ -e /etc/profile.d/zz-env.sh ]; then
     source /etc/profile.d/zz-env.sh
  fi
  
  # Set basic environment variables
  HOME=`pwd`
  export HOME
  USER=`whoami`
  export USER
  HOSTNAME=`hostname -f`
  export HOSTNAME

  # Don't use locale from the ARC CE hosts
  export LANG=en_US.utf8

  # Grid middleware
  if grep -q "CentOS release 6" /etc/redhat-release; then
    source /cvmfs/grid.cern.ch/emi-wn-3.15.3-1_sl6v1/etc/profile.d/setup-wn-example.sh
  elif grep -q "CentOS Linux release 7" /etc/redhat-release; then
    source /cvmfs/grid.cern.ch/centos7-wn-preview-v02/etc/profile.d/setup-c7-wn-example.sh
  else
    echo "ERROR, unexpected /etc/redhat-release contents - no grid middleware available"
  fi

  # Machine job features
  if [ -x /usr/sbin/make-jobfeatures ]; then
     export JOBFEATURES=`/usr/sbin/make-jobfeatures`
  fi

  if [ -d /etc/machinefeatures ] ; then
     export MACHINEFEATURES=/etc/machinefeatures
  fi
  
fi
